.PHONY : clean

buildrootHome=/home/aplex/zengjf/zengjfos/buildroot-2016.08
gccPath=output/host/usr/bin/arm-none-linux-gnueabi-gcc
includePath=output/build/libwebsockets-v1.7.5/lib/
libPath=output/target/usr/lib/

all:
	${buildrootHome}/${gccPath} -I${buildrootHome}/${includePath} -L${buildrootHome}/${libPath} -lwebsockets main.c -o lwsserver

clean:
	rm lwsserver

