buildrootHome=/home/aplex/zengjf/zengjfos/buildroot-2016.08
gccPath=output/host/usr/bin/arm-none-linux-gnueabi-g++

SRC = ARM_WebSocket.cpp \
	  main.cpp \
	  uart/uart.cpp

all:
	${buildrootHome}/${gccPath} \
		-I${buildrootHome}/output/target/include/ \
		-L${buildrootHome}/output/target/lib/ \
		-L${buildrootHome}/output/target/usr/lib/ \
		-lpthread \
		-Iinclude \
		-lwebsockets \
		-ljsoncpp \
		$(SRC) \
		-o lwsserver

.PHONY: clean
clean:
	rm lwsserver

